Repository mash-up-kr/Dionysos-Backend, pull requests merged in 2020-09, with the labels that each got.

#55 Feature/42 readme
  README.md
Labels: 🐢 우선순위 : 하, 📝 문서

#50 #5. 누적 시간 도메인 만들기
  dionysos-api/build.gradle
  dionysos-api/src/main/java/com/dionysos/api/DionysosAPIApplication.java
  dionysos-api/src/main/java/com/dionysos/api/common/response/code/DionysosAPIErrorCode.java
  dionysos-api/src/main/java/com/dionysos/api/common/util/DateUtil.java
  dionysos-api/src/main/java/com/dionysos/api/config/CacheKey.java
  dionysos-api/src/main/java/com/dionysos/api/config/EmbeddedRedisConfig.java
  dionysos-api/src/main/java/com/dionysos/api/config/RedisConfig.java
  dionysos-api/src/main/java/com/dionysos/api/ranking/controller/RankingController.java
  dionysos-api/src/main/java/com/dionysos/api/ranking/dto/ResponseRankingDto.java
  dionysos-api/src/main/java/com/dionysos/api/ranking/dto/ResponseRankingDtoImpl.java
  dionysos-api/src/main/java/com/dionysos/api/ranking/repository/RankingRepository.java
  dionysos-api/src/main/java/com/dionysos/api/ranking/service/RankingService.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/controller/TimeHistoryController.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/dto/RequestSaveTimeHistoryDto.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/dto/RequestTimeHistoryDto.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/dto/ResponseTimeHistoryDto.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/entity/RunningUser.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/entity/TimeHistory.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/exception/NotFoundTimeHistoryException.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/repository/RunningUserRedisRepository.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/repository/TimeHistoryRepository.java
  dionysos-api/src/main/java/com/dionysos/api/timehistory/service/TimeHistoryService.java
  dionysos-api/src/main/java/com/dionysos/api/user/entity/User.java
  dionysos-api/src/main/java/com/dionysos/api/user/repository/UserRepository.java
  dionysos-api/src/main/resources/application-redis.properties
  dionysos-api/src/main/resources/application.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: ‼ 우선순위 : 상, 🤔 이야깃거리, 🤖 기능

#57 chore: #56. AppSpec.YML 파일 권한 수정
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
Labels: ‼ 우선순위 : 상
